trigger:
  branches:
    include:
      - main  # ✅ Enables CI on the main branch

pool:
  vmImage: ubuntu-latest

steps: 
- script: chmod +x gradlew
  displayName: 'Make Gradlew Executable'

- task: JavaToolInstaller@1
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQubeFeb2025'
    scannerMode: 'other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=Feb2025-Java-Gradle-CI-Using-UI-Approach_Feb2025-Java-Gradle-CI-Using-UI-Approach_27a4f7d9-177c-4d53-bed9-35cd910fd0bd
      sonar.projectName=Feb2025-Java-Gradle-CI-Using-UI-Approach


- script: chmod +x gradlew
  displayName: 'Make Gradlew Executable'
- task: Gradle@4
  displayName: 'Build Java Project'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'  # ✅ Ensure correct JDK version
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '6.0.1.5171'
    spotBugsAnalysis: false

- task: SonarQubeAnalyze@7
  displayName: 'Run SonarQube Analysis'

- task: SonarQubePublish@7
  displayName: 'Publish SonarQube Results'
  inputs:
    pollingTimeoutSec: '300'